CREATE TABLE USER(USERID VARCHAR(50), PASSWORD_HASH VARCHAR(100) NOT NULL, NAME VARCHAR(100) NOT NULL, ROLE VARCHAR(20) NOT NULL, PHONE VARCHAR(20), EMAIL VARCHAR(100), STATUS VARCHAR(20) NOT NULL, PRIMARY KEY (USERID));

CREATE TABLE PLAYER(ID INT AUTO_INCREMENT, NAME VARCHAR(100) NOT NULL, UTR_GROUP INT, ORGS VARCHAR(100), PRIMARY KEY (ID));

CREATE TABLE TOURNAMENT(ID VARCHAR(8) PRIMARY KEY, ORGANIZER VARCHAR(20) NOT NULL, NAME VARCHAR(100) NOT NULL, VENUE VARCHAR(20) NOT NULL, DATE DATE, TYPE VARCHAR(50) NOT NULL, STATUS VARCHAR(50) NOT NULL, BEST_OF_N_SETS INT NOT NULL);

CREATE TABLE TOURNAMENT_REGISTRATION(TOURNAMENT_ID VARCHAR(8), PLAYER_ID VARCHAR(50), DATETIME DATETIME NOT NULL, PRIMARY KEY(TOURNAMENT_ID, PLAYER_ID));

CREATE TABLE TOURNAMENT_CONTESTANT(TOURNAMENT_ID VARCHAR(8), PLAYER_ID VARCHAR(50), RANK_NUMBER INT, PRIMARY KEY(TOURNAMENT_ID, PLAYER_ID));

CREATE TABLE TENNIS_MATCH(ID INT PRIMARY KEY AUTO_INCREMENT, TOURNAMENT_ID VARCHAR(8), TOURNAMENT_BOARD_NUMBER INT, TOURNAMENT_MATCH_NUMBER INT, PLAYER1_ID VARCHAR(50), PLAYER2_ID VARCHAR(50), DATETIME DATETIME, RESULT VARCHAR(50), PLAYER1_UTR DECIMAL(5,2), PLAYER2_UTR DECIMAL(5,2), MATCH_UTR_FOR_PLAYER1 DECIMAL(5,2), MATCH_UTR_FOR_PLAYER2 DECIMAL(5,2));
