SELECT * FROM TENNIS_MATCH WHERE PLAYER1_ID <> 0 AND PLAYER1_ID NOT IN (SELECT ID FROM PLAYER) OR PLAYER2_ID <> 0 AND PLAYER2_ID NOT IN (SELECT ID FROM PLAYER);

SELECT * FROM TENNIS_MATCH WHERE DATETIME IS NULL AND RESULT IS NOT NULL;